name: PR Size Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions;
            const deletions = pr.deletions;
            const total = additions + deletions;

            if (total > 500) {
              core.setFailed(
                `PR too large (${total} lines). Split into smaller PRs.`
              );
            }